@echo off
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\about_viper
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\aiqicha_api
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\ai_agent
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\automation
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\avoid_tracing
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\change_password
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\common_config
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\credential
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\dingding_bot
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\file_explorer
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\fofa_api
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\getting_start
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\handler_and_payload
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\handler_firewall
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\host_and_session_list
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\hunter_api
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\information
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\installation_directory_introduction
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\internet_scan
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\issues
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\license
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\msfconsole
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\openai_api
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\open_source_software
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\os_optimization
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\passive_scan
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\portfwd
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\portservice
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\quake_api
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\realtime
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\routeproxy
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\runningjob
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\run_module
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\server_bot
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\session_monitor
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\shutdown_restart
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\smtp_config
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\telegram_bot
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\terminate
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\try_viper
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\update_version
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\user_management
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\vulnerability
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\web_delivery
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\welcome_to_viper
mkdir C:\git\AIPLATFORM\docs\en\guide\webp\zoomeye_api
echo All English guide webp directories created successfully!
